///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UrlandVersionModal {
/*
{
  "latest_version": "2.0.0",
  "url": "https://drive.google.com/file/d/1s7F_wo_RHrQP0qjNCDj-PnU4GkQa1aGP/view?usp=sharing"
} 
*/

  String? latestVersion;
  String? url;

  UrlandVersionModal({
    this.latestVersion,
    this.url,
  });
  UrlandVersionModal.fromJson(Map<String, dynamic> json) {
    latestVersion = json['latest_version']?.toString();
    url = json['url']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['latest_version'] = latestVersion;
    data['url'] = url;
    return data;
  }
}
